### ISSUE TITLE
Issue when self compiling

### ISSUE THREAD

**Issue by o10collin** [outspect/outspect-1v1.lol-cheat#3]
![image](https://github.com/outspect/outspect-1v1.lol-cheat/assets/141531740/4bcd9fb3-59d9-41a5-8e67-59b8bc5a4fd3)
> 78 Warnings and 12 Errors when compiling the Code myself

**Comment by outspect** [comment]
you need to add the references for 1v1.lol

**Comment by keplerHaloxx** [comment]
> you need to add the references for 1v1.lol

how would you do that? i found the dlls inside `C:\Program Files (x86)\Steam\steamapps\common\1v1.LOL\1v1_LOL_Data\Managed` and i'm trying to add the references into visual studio by right clicking the references thing inside the solution explorer then clicking add reference then browse and selecting all the dll's but it does not work

nvm i figured it out
