### ISSUE TITLE
References Missing

### ISSUE THREAD

**Issue by paysonism** [outspect/outspect-1v1.lol-cheat#4]
Hey man this looks like a really good source and I'm trying to get it to work but all of the references are missing. Could you send them to me as I don't know what the reference "1v1" is. Thanks!

**Comment by paysonism** [comment]
sorry not all of them but all of the photon ones, the unity ones, and the 1v1 (whatever that is lmao). But if you could just .rar all the references and send them to me that would be great or if u know a way to fix.

**Comment by outspect** [comment]
they are in the 1v1.lol data managed folder

**Comment by paysonism** [comment]
thx
